variables:
  APP_NAME: "youness-staticwebsite"
  APP_CONTAINER_PORT: "80"
  APP_EXPOSED_PORT: "80"
  HEROKU_APP_STG: "chocoapp-staging"
  HEROKU_APP_PROD: "chocoapp-prod"
  HEROKU_DEMAIN: "herokuapp.com"

image: docker:latest
services:
  - name: docker:dind
    alias: docker

stages:
  - Build image
  - Test acceptation
  - Release image
  - Deploy review
  - Stop review
  - Deploy staging
  - Test staging
  - Deploy prod
  - Test prod

.test_template: &test
  image: alpine
  script:
    - apk --no-cache add curl
    - curl "http://$DOMAIN" | grep -i "Dimension" 
docker-build:
  stage: Build image
  script:
    - docker build -t ${APP_NAME} .
    - docker save ${APP_NAME} > ${APP_NAME}.tar
  artifacts:
    paths:
      - "${APP_NAME}.tar"
    when: on_success
    expire_in: 2 days

test acceptation:
  stage: Test acceptation
  script:
    - docker load < ${APP_NAME}.tar
    - docker run -d -p ${TEST_PORT}:${INTERNAL_PORT}  --name webapp ${APP_NAME}
    - apk --no-cache add curl
    - sleep 5
    - curl "http://docker:${TEST_PORT}" | grep -i "Dimension"

release image:
  stage: Release image
  script:
    - docker load < ${APP_NAME}.tar
    - docker tag ${APP_NAME} "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
    - docker tag ${APP_NAME} "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
    - docker push "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"

deploy staging:
  stage: Deploy staging
  environment:
    name: staging
    url: http://${HEROKU_APP_STG}.${HEROKU_DEMAIN}
  script:
    - apk --no-cache add npm
    - npm install -g heroku  
    - heroku container:login 
    - heroku create &{HEROKU_APP_STG} || echo "Project already exist"
    - heroku container:push -a  &{HEROKU_APP_STG} web
    - heroku container:release -a  &{HEROKU_APP_STG} web

deploy prod:
  stage: Deploy prod
  environment:
    name: prod
    url: http://${HEROKU_APP_PROD}.${HEROKU_DEMAIN}
  only :
    - master
  script:
    - apk --no-cache add npm
    - npm install -g heroku  
    - heroku container:login 
    - heroku create &{HEROKU_APP_PROD} || echo "Project already exist"
    - heroku container:push -a  &{HEROKU_APP_PROD} web
    - heroku container:release -a  &{HEROKU_APP_PROD} web

deploy review:
  stage: Deploy review
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://chocoapp-$CI_COMMIT_REF_NAME.${HEROKU_DEMAIN:}
    on_stop: stop review
  only:
    - merge_requests
  script:
    - apk --no-cache add npm
    - npm install -g heroku  
    - heroku container:login 
    - heroku create chocoapp-$CI_COMMIT_REF_NAME || echo "Project already exist"
    - heroku container:push -a chocoapp-$CI_COMMIT_REF_NAME web
    - heroku container:release -a chocoapp-$CI_COMMIT_REF_NAME web
stop review:
  stage: Stop review
  variables:
    GIT_STRATEGY: none
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  only:
    - merge_requests
  when: manual
  script:
    - apk --no-cache add npm
    - npm install -g heroku
    - heroku container:login
    - heroku apps:destroy -a chocoapp-$CI_COMMIT_REF_NAME -c chocoapp-$CI_COMMIT_REF_NAME

test staging:
  <<: *test
  variables:
    DOMAIN: ${HEROKU_APP_STG}.${HEROKU_DEMAIN}

test prod:
  <<: *test
  only:
    - main
  variables:
    DOMAIN: ${HEROKU_APP_PROD}.${HEROKU_DEMAIN}
  

